[package]
name = "bevy_garage_camera"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
bevy = { workspace = true, default-features = false }
bevy_garage_car = { workspace = true }
bevy_rapier3d = { workspace = true }
